### ISSUE TITLE
Broken font rendering

### ISSUE THREAD

**Issue by Avadon** [ZunamiLab/ZunamiUI#17]
After some tests it turns out that font antialiased render mode should fix the issue.

![alt text](https://i.ibb.co/88Y3jX0/font-test.png "Font render test")

@ArtemiyShibanov good enough?

**Comment by Avadon** [comment]
@ArtemiyShibanov https://font.zunami.io можно посмотреть вживую тут

**Comment by Avadon** [comment]
You can check the fixed version at app.zunami.io

**Comment by ArtemiyShibanov** [comment]
The font looks narrow. Please tell me is this Vela Sans?

**Comment by Avadon** [comment]
Nope, "Anderson Grotesk" as it was in Figma mockup

**Comment by ArtemiyShibanov** [comment]
I don't understand why the font looks narrow
