### ISSUE TITLE
Orange stripe

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#27]
There is no orange stripe near the section on which we are now. The orange stripe in this case should be near the Dashbord. When switching sections, it should move to other sections

**Comment by Avadon** [comment]
You can check the fixed version at app.zunami.io

**Comment by ArtemiyShibanov** [comment]
Thank you! Orange stripe should be rounded. Please see in Figma 🙏🏼

**Comment by Avadon** [comment]
Check updated version here: https://stripe.zunami.io/

**Comment by ArtemiyShibanov** [comment]
Everything is okay! Thank you! 🙏🏼
