### ISSUE TITLE
DAO, USD, USDT icons are located too close to the left

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#29]
In the Deposit and Withdraw sections, the DAO, USD, USDT icons are located too close to the left. The distance between the icons and the names of stablecoins is also violated.

**Comment by Avadon** [comment]
Updated version at https://dev.zunami.io. Is it better now?
![alt text](https://i.ibb.co/yPhmV4J/Screen-Shot-2021-12-15-at-23-58-44-copy.png "Title")

**Comment by ArtemiyShibanov** [comment]
Looks good 🙏🏼
