### ISSUE TITLE
Withdraw incorrect arrow

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#30]
In the Withdraw section in the header, the arrow on the right should be different.

**Comment by Avadon** [comment]
Check the fixed version at https://app.zunami.io

**Comment by ArtemiyShibanov** [comment]
Everything is ok! Thank you!🙏🏼

**Comment by ArtemiyShibanov** [comment]
@Avadon Unfortunately, the bug persists in the mobile version. The arrow comes out from behind the mask in the Deposit and Withdraw button. 
<img width="1264" alt="Снимок экрана 2021-12-09 в 23 40 15" src="https://user-images.githubusercontent.com/91192909/145472335-6266bd3f-39d7-4743-b9d4-d15ae362b567.png">
s

**Comment by Avadon** [comment]
Check it again, please. Should be fixed

**Comment by ArtemiyShibanov** [comment]
🙏🏼
