### ISSUE TITLE
Incorrect size of white plate

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#31]
In the Deposit and Withdraw sections, the white plate on the back, on the right, extends beyond the boundaries of the Connect Wallet button

**Comment by Avadon** [comment]
@ArtemiyShibanov Would you be so kind to make a screenshot if it's still actual at http://dev.zunami.io?

**Comment by ArtemiyShibanov** [comment]
Thank you!
