### ISSUE TITLE
How to use and Light Mode buttons in Dark Mode

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#32]
In Dark Mode, on hover, the How to use and Light Mode buttons should turn dark like in the Figma layout. Now they are painted in a light shade.

**Comment by Avadon** [comment]
Check out fixed version at https://32.zunami.io/

**Comment by ArtemiyShibanov** [comment]
Thank you! Bug was fixed. 🙏🏼
But Connect wallet button became bigger than usual in 1024 px layout. I attach the photo

<img width="1176" alt="Снимок экрана 2021-12-08 в 12 39 30" src="https://user-images.githubusercontent.com/91192909/145185299-d7e2627b-1be0-483b-a7ab-592d9e996b38.png">

**Comment by ArtemiyShibanov** [comment]
I'm sorry. It's correct photo 
<img width="1215" alt="Снимок экрана 2021-12-08 в 12 42 07" src="https://user-images.githubusercontent.com/91192909/145185722-c2af96b8-f4f9-4c19-82d0-cb629c320a7e.png">

**Comment by Avadon** [comment]
Is it the version you see at https://32.zunami.io? Cause that's what I see in 1024x768:
![Screenshot](https://i.ibb.co/wzwqGCk/Screen-Shot-2021-12-08-at-12-45-36.png)
![Screenshot](https://i.ibb.co/HCJsZJp/Screen-Shot-2021-12-08-at-12-45-32.png)

**Comment by ArtemiyShibanov** [comment]
https://user-images.githubusercontent.com/91192909/145419149-748e24c3-28a2-400d-ab9c-daa73d5963ba.mov
