### ISSUE TITLE
Donut chart is not displayed in all layouts

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#34]
Donut chart is not displayed in all layouts

**Comment by Avadon** [comment]
Check out fixed version at https://chart.zunami.io/

**Comment by ArtemiyShibanov** [comment]
Width of chart too thin. Please see in Figma

**Comment by Avadon** [comment]
Can you please check it again. Is it better?

**Comment by ArtemiyShibanov** [comment]
It's good! Thank you! 🙏
