### ISSUE TITLE
1024 px problems

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#36]
Layout with a width of 1024 - adapts correctly. However, the white bar in the Dashboard, Deposit, Withdraw sections does not extend to the right to the right edge of the Connect wallet button. The arrow in the header of the Withdraw section also looks the other way

**Comment by Avadon** [comment]
Now it's full height, check the updated version at https://1024.zunami.io
All pages and elements for 1024 resolution should be ok

**Comment by ArtemiyShibanov** [comment]
Everything is correct! Thank you!
