### ISSUE TITLE
Buttons overlap in iPhone 13 Layout 

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#38]
On the main screen, the orange Deposit and Withdraw buttons overlap and merge

**Comment by ArtemiyShibanov** [comment]
The same situation with Withdraw and Withdraw all buttons in this layouts:
<img width="974" alt="Снимок экрана 2021-12-10 в 11 40 27" src="https://user-images.githubusercontent.com/91192909/145543637-fb0015f4-8af4-4fce-9168-35cd87bcdb9a.png">
<img width="494" alt="Снимок экрана 2021-12-10 в 11 40 46" src="https://user-images.githubusercontent.com/91192909/145543675-423306aa-ab90-47ab-a7b2-6e2ba00a9b48.png">

**Comment by Avadon** [comment]
Check the fixed version at https://38.zunami.io/

**Comment by Avadon** [comment]
As far as I know now we have only one "Withdraw/Deposit" button, su I guess this issue can be closed? @senichevalexey

**Comment by senichevalexey** [comment]
It is not a bug
