### ISSUE TITLE
IPhone 13 incorrect Dashboard plate

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#39]
In the Dashboard plate there is an arrow from the Deposit section instead of rectangles

**Comment by Avadon** [comment]
Should be ok by now. Check https://app.zunami.io

**Comment by ArtemiyShibanov** [comment]
Problem shouldn't fixed 😒

**Comment by Avadon** [comment]
Fixed at https://dev.zunami.io

![alt text](https://i.ibb.co/2tN7LBH/Screen-Shot-2021-12-16-at-00-49-24.png "Title")

**Comment by ArtemiyShibanov** [comment]
In dark version the problem still saves

**Comment by Avadon** [comment]
Should be good now (https://dev.zunami.io):

![alt text](https://i.ibb.co/hVrbf2Z/Screen-Shot-2021-12-16-at-11-57-59.png "Title")
![alt text](https://i.ibb.co/yk5nZwk/Screen-Shot-2021-12-16-at-11-58-06.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
