### ISSUE TITLE
Rectangles are displayed incorrectly in the Dashboard section iPhone 13

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#41]
When switching the mode to dark, rectangles are displayed incorrectly in the Dashboard section, everything merges.

**Comment by Avadon** [comment]
Check out the updated version at https://dev.zunami.io

**Comment by Avadon** [comment]
Fixed:

![alt text](https://i.ibb.co/q5ry6zF/Screen-Shot-2021-12-16-at-00-33-27.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
