### ISSUE TITLE
Incorrect The Connect wallet button iPhone 13

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#42]
The Connect wallet button looks different, the plus sign on the top right is missing.

**Comment by Avadon** [comment]
Check the fixed version at https://42.zunami.io/

![alt text](I[solated.png](https://i.ibb.co/hZR5fjR/Screen-Shot-2021-12-13-at-10-51-11.png) "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you! Everything is correct! 🙏🏼
