### ISSUE TITLE
The orange Deposit and Withdraw buttons must not be displayed iPhone 13

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#43]
On the Deposit and Withdraw screens, the orange Deposit and Withdraw buttons must not be displayed. They fool the user into clicking the cross to return to the Dashboard

**Comment by Avadon** [comment]
Check out the updated version at https://dev.zunami.io

**Comment by Avadon** [comment]
As for now they're not visible in Deposit/Withdraw screens:
![alt text](https://i.ibb.co/NtQxZt3/Screen-Shot-2021-12-16-at-00-31-05.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
