### ISSUE TITLE
Design : Show pending deposits

### ISSUE THREAD

**Issue by bitok228** [ZunamiLab/ZunamiUI#50]
On page /deposit need show pendingDeposits (when a user sends a transaction his transaction goes to pending, until we approve it). We need to display this deposit until the moment of approval, for example, at the bottom under the deposit.

**Comment by ArtemiyShibanov** [comment]
The caption will appear in the new interface design soon. An existing UI layout can use the loading state text style
<img width="881" alt="Снимок экрана 2021-12-20 в 15 47 05" src="https://user-images.githubusercontent.com/91192909/146738850-210e6cea-92ff-416b-95cd-95711239b047.png">
.
