### ISSUE TITLE
Incorrect text centering

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#68]
Please center the text inside the diagram like in the Figma layout
<img width="189" alt="Снимок экрана 2021-12-16 в 11 47 46" src="https://user-images.githubusercontent.com/91192909/146309986-b09dbee1-3bb3-4171-bf89-665557e552a7.png">

**Comment by Avadon** [comment]
It should be fixed by now at https://dev.zunami.io
![alt text](https://i.ibb.co/pfXw7kf/Screen-Shot-2021-12-16-at-13-42-17.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
