### ISSUE TITLE
Incorrect Line break

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#69]
Incorrect Line break in mobile version
<img width="131" alt="Снимок экрана 2021-12-16 в 11 51 42" src="https://user-images.githubusercontent.com/91192909/146310309-d6edea0b-33ea-4092-a36c-bed8c058b157.png">

**Comment by Avadon** [comment]
Should be good now (https://dev.zunami.io) in both versions:

![alt text](https://i.ibb.co/hVrbf2Z/Screen-Shot-2021-12-16-at-11-57-59.png "Title")
![alt text](https://i.ibb.co/yk5nZwk/Screen-Shot-2021-12-16-at-11-58-06.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
