### ISSUE TITLE
Incorrect video integration

### ISSUE THREAD

**Issue by ArtemiyShibanov** [ZunamiLab/ZunamiUI#70]
Video is out of the box
<img width="330" alt="Снимок экрана 2021-12-16 в 11 53 52" src="https://user-images.githubusercontent.com/91192909/146310506-34807839-9d5e-4124-aab6-d533fa492cb9.png">
x

**Comment by Avadon** [comment]
Both desktop/mobile should be correct at https://dev.zunami.io

![alt text](https://i.ibb.co/Qv3WWzN/Screen-Shot-2021-12-16-at-11-03-54.png "Title")
![alt text](https://i.ibb.co/pQBWXH2/Screen-Shot-2021-12-16-at-10-55-55.png "Title")

**Comment by ArtemiyShibanov** [comment]
Thank you!
